# ---------------------- #
# container/reusable.yml #
# ---------------------- #

# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases

# Reusable container definition

# In the following example, the containers are defined in the resources section.
# Each container is then referenced later, by referring to its assigned alias.
# (Here, we explicitly list the jobs keyword for clarity.)

resources:
  containers:
  - container: u14
    image: ubuntu:14.04

  - container: u16
    image: ubuntu:16.04

  - container: u18
    image: ubuntu:18.04

jobs:
- job: RunInContainer
  pool:
    vmImage: 'ubuntu-18.04'

  strategy:
    matrix:
      ubuntu14:
        containerResource: u14
      ubuntu16:
        containerResource: u16
      ubuntu18:
        containerResource: u18

  container: $[ variables['containerResource'] ]

  steps:
  - script: |
      "printf Running on: $(Agent.OS)"
      "printf Environment: $(printenv)"


# EOF #
